include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    prefer_double_quotes: true
    prefer_single_quotes: false
    public_member_api_docs: false

formatter:
  page_width: 90
  trailing_commas: preserve 

analyzer:
  plugins:
    - custom_lint
